const API_BASE = 'http://localhost:5000/api';

// Load data from Python backend
async function loadDataFromPython() {
  try {
    console.log("Loading data from Python backend...");

    const response = await fetch(`${API_BASE}/load-data`);
    const result = await response.json();

    if (result.status === 'success') {
      console.log("Data loaded from Python backend:", result);

      // Use data from Python app
      return {
        years: result.years || [],
        indicators: result.series || [],
        countries: result.countries || [],
      };
    }
    throw new Error(result.message);
  } catch (error) {
    console.error("Failed to load from Python backend:", error);
    // Show error to user
    document.getElementById("summaryContent").innerHTML =
      `<p style="color: red;">Error: Cannot connect to Python backend. Make sure api_connection.py is running.</p>`;
    return { years: [], indicators: [], countries: [] };
  }
}

// Initialize with Python data only
async function initializeDashboard() {
  await checkDataStatus();
  return loadDataFromPython();
}

// Data Management Functions
async function checkDataStatus() {
    const statusElement = document.getElementById('dataStatus');
    const messageElement = document.getElementById('uploadMessage');

    statusElement.textContent = 'Checking...';
    statusElement.className = 'status-checking';
    messageElement.innerHTML = '';

    try {
        const response = await fetch(`${API_BASE}/check-data-status`);
        const result = await response.json();

        if (result.status === 'success') {
            statusElement.textContent = result.data_available ? 'Data Available' : 'No Data Found';
            statusElement.className = result.data_available ? 'status-available' : 'status-missing';

            if (!result.data_available) {
                messageElement.innerHTML = '<div class="message info">Please upload a CSV file to get started</div>';
            }
        }
    } catch (error) {
        statusElement.textContent = 'Check Failed';
        statusElement.className = 'status-missing';
        messageElement.innerHTML = `<div class="message error">Unable to check data status: ${error.message}</div>`;
    }
}

async function uploadCSV() {
    const fileInput = document.getElementById('csvUpload');
    const messageElement = document.getElementById('uploadMessage');

    if (!fileInput.files.length) {
        messageElement.innerHTML = '<div class="message error">Please select a CSV file first</div>';
        return;
    }

    const file = fileInput.files[0];
    if (!file.name.toLowerCase().endsWith('.csv')) {
        messageElement.innerHTML = '<div class="message error">Please select a CSV file</div>';
        return;
    }

    messageElement.innerHTML = '<div class="message info">Uploading and processing file... This may take a moment.</div>';

    try {
        const formData = new FormData();
        formData.append('file', file);

        const response = await fetch(`${API_BASE}/upload-csv`, {
            method: 'POST',
            body: formData
        });

        const result = await response.json();

        if (result.status === 'success') {
            messageElement.innerHTML = `<div class="message success">${result.message}</div>`;

            // Refresh the data and update the dashboard
            setTimeout(() => {
                checkDataStatus();
                location.reload(); // Reload to refresh all data
            }, 2000);

        } else {
            messageElement.innerHTML = `<div class="message error">Upload failed: ${result.message}</div>`;
        }

    } catch (error) {
        messageElement.innerHTML = `<div class="message error">Upload error: ${error.message}</div>`;
    }
}

// Generate chart using Python backend
async function generateChartWithPython(series, countries, years, chartType = 'line') {
  try {
    console.log("📊 Requesting chart from Python:", { series, countries, years, chartType });

    const response = await fetch(`${API_BASE}/generate-chart`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        series: series,
        countries: countries,
        years: years,
        chart_type: chartType
      })
    });

    const result = await response.json();
    console.log("📊 Chart response:", result);

    if (result.status === 'success') {
      // Display the chart image from Python
      const chartContainer = document.getElementById("chartContainer");
      chartContainer.innerHTML = `
        <div class="python-chart">
          <img src="${result.chart_image}" alt="Generated Chart" style="max-width: 100%; height: auto;">
          <p class="chart-source">📊 Chart generated by your Python app</p>
        </div>
      `;
      return result.country_data;
    } else {
      console.error("Chart generation failed:", result.message);
    }
  } catch (error) {
    console.log("Chart generation failed:", error);
  }
  return null;
}

// Get AI insights from Python
async function getAIInsights(indicator, countryA, countryB) {
  try {
    const response = await fetch(`${API_BASE}/get-insights`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        series: indicator,
        countries: [countryA, countryB].filter(c => c),
        years: []
      })
    });

    const result = await response.json();
    return result.status === 'success' ? result.insights : null;
  } catch (error) {
    return null;
  }
}

// Add AI features to summary
function enhanceSummaryWithAI(summaryElement, indicator, countryA, countryB) {
  const aiSection = document.createElement('div');
  aiSection.className = 'ai-features';
  aiSection.innerHTML = `
    <h4>🤖 AI Analysis</h4>
    <button onclick="showAIInsights('${indicator}', '${countryA}', '${countryB}')" class="ai-btn">
      Get AI Insights
    </button>
  `;
  summaryElement.appendChild(aiSection);
}

// Display AI insights
async function showAIInsights(indicator, countryA, countryB) {
  const insights = await getAIInsights(indicator, countryA, countryB);
  const summaryContent = document.getElementById("summaryContent");

  if (insights) {
    summaryContent.innerHTML = `
      <div class="ai-insights">
        <h3>🤖 AI Analysis: ${indicator}</h3>
        <div class="insight-text">${insights}</div>
        <button onclick="updateChart()" class="back-btn">← Back to Chart</button>
      </div>
    `;
  } else {
    summaryContent.innerHTML += `<p class="ai-error">AI insights currently unavailable</p>`;
  }
}

// Use initializeDashboard
initializeDashboard().then(({ years, indicators, countries }) => {
  console.log("Initializing dashboard with data:", {
    yearsCount: years.length,
    indicatorsCount: indicators.length,
    countriesCount: countries.length
  });

  const indicatorSel = document.getElementById("indicatorSelect");
  const countryASel = document.getElementById("countryA");
  const countryBSel = document.getElementById("countryB");
  const yearSel = document.getElementById("yearSelect");
  const showChange = document.getElementById("showChange");

  // Clear existing options first
  indicatorSel.innerHTML = '<option value="">-- Select Indicator --</option>';
  countryASel.innerHTML = '<option value="">-- Select Country A --</option>';
  countryBSel.innerHTML = '<option value="">-- Select Country B --</option>';
  yearSel.innerHTML = '<option value="">-- All Years --</option>';

  // Populate dropdowns from Python data
  indicators.forEach(item => {
    const name = item.name || item.value || item;
    const value = item.value || item.name || item;
    indicatorSel.add(new Option(name, value));
  });

  countries.forEach(item => {
    const name = item.name || item.value || item;
    const value = item.value || item.name || item;
    countryASel.add(new Option(name, value));
    countryBSel.add(new Option(name, value));
  });

  years.forEach(item => {
    const name = item.name || item.value || item;
    const value = item.value || item.name || item;
    yearSel.add(new Option(name, value));
  });

  console.log("Dropdowns populated:", {
    indicators: indicatorSel.options.length,
    countries: countryASel.options.length,
    years: yearSel.options.length
  });

  // Update chart using Python backend
  async function updateChart() {
    const indicator = indicatorSel.value;
    const countryA = countryASel.value;
    const countryB = countryBSel.value;
    const selectedYear = yearSel.value;

    console.log("Updating chart:", { indicator, countryA, countryB, selectedYear });

    if (!indicator) {
      document.getElementById("summaryContent").innerHTML = "<p>Please select an indicator</p>";
      return;
    }

    const countriesToShow = [countryA, countryB].filter(c => c);
    if (countriesToShow.length === 0) {
      document.getElementById("summaryContent").innerHTML = "<p>Please select at least one country</p>";
      return;
    }

    document.getElementById("summaryContent").innerHTML = "<p>Generating chart with Python backend...</p>";

    const yearsToShow = selectedYear ? [selectedYear] : (years.map(item => item.value || item.name || item));
    const chartType = selectedYear ? 'bar' : 'line';

    const countryData = await generateChartWithPython(indicator, countriesToShow, yearsToShow, chartType);

    if (countryData) {
      // Show AI features after chart is generated
      const summaryContent = document.getElementById("summaryContent");
      summaryContent.innerHTML = `
        <div class="summary-info">
          <h3>${indicator}</h3>
          <p>Chart generated successfully for ${countriesToShow.join(', ')}</p>
        </div>
      `;

      // Add AI features
      const aiSection = document.createElement('div');
      aiSection.className = 'ai-features';
      aiSection.innerHTML = `
        <h4>🤖 AI Analysis</h4>
        <button onclick="getAIInsightsForChart('${indicator}', '${countryA}', '${countryB}')" class="ai-btn">
          Get AI Insights
        </button>
      `;
      summaryContent.appendChild(aiSection);
    } else {
      document.getElementById("summaryContent").innerHTML =
        "<p style='color: red;'>Failed to generate chart. Check Python backend.</p>";
    }
  }

  // AI function for chart
  window.getAIInsightsForChart = async function(indicator, countryA, countryB) {
    const insights = await getAIInsights(indicator, countryA, countryB);
    const summaryContent = document.getElementById("summaryContent");

    if (insights) {
      summaryContent.innerHTML = `
        <div class="ai-insights">
          <h3>🤖 AI Analysis: ${indicator}</h3>
          <div class="insight-text">${insights}</div>
          <button onclick="updateChart()" class="back-btn">← Back to Chart</button>
        </div>
      `;
    } else {
      summaryContent.innerHTML += `<p class="ai-error">AI insights currently unavailable</p>`;
    }
  };

  // Event listeners
  [indicatorSel, countryASel, countryBSel, yearSel, showChange].forEach(el =>
    el.addEventListener("change", updateChart)
  );
});